[build-system]
requires = ["setuptools","wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "expresswrite"
version = "0.1"
description = "express"

[project.scripts]
expresswrite = "app:main"

[tool.distutils.bdist_wheel]
universal = true